# NumPy and SciPy

NumPy and SciPy are the twin pillars of doing data science in Python.  Early on in Python's history, it became clear that Python's list data structures weren't ideal for doing heavy-duty number crunching on vectors and matrices. 

So, numpy was born to try to solve the problem, and introduce an array-type data structure into Python.

Let's first create an array:

In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

Notice that we have to pass in a list of numbers rather than 

np.array(1,2,3)  ## ERROR: won't work

np.array([1,2,3]) ## Correct

Let's do a sequence of numbers with arange

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Try to multiply sequence by a scalar
np.arange(10) * np.pi

array([ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
       15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388])

We can make multi-dimensional arrays from single dimensions with shape.

In [4]:
a = np.array([1,2,3,4,5,6])
a.shape = (2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

We can access elements of the 2-D array using array subscription operators.

Remember we do **this**:

```python
a[1,2]
```

not **this**

```python
a[1][2] # BAD!
```

In [14]:
## TODO: Slice the first (zeroeth) row of 2-D array a.
b = a[0,:]
print(b)

[1 2 3]


In [16]:
## TODO: Slice the first (zeroeth) column of 2-D array a
c = a[:, 0]
print(c)

[1 4]


In [19]:
## Access the element at column number 1 (counting from zero), 
# and row number 0:

d = a[0,1]
print(d)

2


### Matrices

We can make matrices

In [20]:
np.matrix('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

Matrix multiplication requires the use of matrices.

In [23]:
## Matrix Multiply

a1 = np.matrix('1 2; 3 4')
a2 = np.matrix('3 4; 5 7')
a1 * a2
a1

matrix([[1, 2],
        [3, 4]])

In [26]:
# Converting an array to a matrix
ab = np.array([1,2,3,4])
mat_a = np.mat(ab)
mat_a.reshape(2,2)

matrix([[1, 2],
        [3, 4]])

### Sparse Matrices

Sometimes we may have sparse data and want to store a sparse matrix

In [37]:
import numpy, scipy.sparse
n = 100000
x = (numpy.random.rand(n) * 2).astype(int).astype(float) # 50% sparse vector
x_csr = scipy.sparse.csr_matrix(x)
x_dok = scipy.sparse.dok_matrix(x.reshape(x_csr.shape))

x_dok
#len(x)
print(x)
type(x)
x.*?

[1. 1. 1. ... 1. 0. 0.]


x.T
x.__abs__
x.__add__
x.__and__
x.__array__
x.__array_finalize__
x.__array_function__
x.__array_interface__
x.__array_prepare__
x.__array_priority__
x.__array_struct__
x.__array_ufunc__
x.__array_wrap__
x.__bool__
x.__class__
x.__complex__
x.__contains__
x.__copy__
x.__deepcopy__
x.__delattr__
x.__delitem__
x.__dir__
x.__divmod__
x.__doc__
x.__eq__
x.__float__
x.__floordiv__
x.__format__
x.__ge__
x.__getattribute__
x.__getitem__
x.__gt__
x.__hash__
x.__iadd__
x.__iand__
x.__ifloordiv__
x.__ilshift__
x.__imatmul__
x.__imod__
x.__imul__
x.__index__
x.__init__
x.__init_subclass__
x.__int__
x.__invert__
x.__ior__
x.__ipow__
x.__irshift__
x.__isub__
x.__iter__
x.__itruediv__
x.__ixor__
x.__le__
x.__len__
x.__lshift__
x.__lt__
x.__matmul__
x.__mod__
x.__mul__
x.__ne__
x.__neg__
x.__new__
x.__or__
x.__pos__
x.__pow__
x.__radd__
x.__rand__
x.__rdivmod__
x.__reduce__
x.__reduce_ex__
x.__repr__
x.__rfloordiv__
x.__rlshift__
x.__rmatmul__
x.__rmod__
x.__rmul__
x.__ror__
x.__rpow__
x.__rrshift__



### Loading from CSV file

We can load from a CSV file

In [27]:
import csv
with open('../data/array/array.csv', 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    data = []
    for row in csvreader:
        row = [float(x) for x in row]
        data.append(row)

data



[[2.0, 3.0, 4.0, 5.0], [3.0, 4.0, 5.0, 6.0], [7.0, 9.0, 9.0, 10.0]]

### Solving a matrix 

In [28]:
import numpy as np
import scipy as sp
a = np.array([[3,2,0],[1,-1,0],[0,5,1]])
b = np.array([2,4,-1])
x = np.linalg.solve(a,b)
x



array([ 2., -2.,  9.])

In [29]:
#Checking the answer

np.dot(a, x) == b


array([ True,  True,  True])